### ISSUE TITLE
Mantener sesión

### ISSUE THREAD

**Issue by kanales** [UB-ES-19/F1-Oportunista#16]
US2 - Una vez se hace login se tiene que mantener la sesión hasta que el usuario hace logout.

**Comment by kanales** [comment]
Si credenciales en el form de `/login/` son correctas:
    Redirect a home
Si credenciales en el form de `/login/` son incorrectas:
    HTTP error 401 "Unauthorized"
Si request.user.is_authenticated:
    el usuario ha iniciado sesion
Cualquier request a `/logout/` cierra la sesión

**Comment by aadevafi7** [comment]
Aprobado pull request. EL usuario puede loggearse.
