### ISSUE TITLE
Elegir y migrar BD (NO aplicar hasta migración a Docker)

### ISSUE THREAD

**Issue by aadevafi7** [UB-ES-19/F1-Oportunista#30]
Elegir gestor de base de datos donde migrar la SQLite antes del sprint 5 (en teoria último sprint) y modificar lo que se tenga que modificar para aplicar el cambio.

**Comment by aadevafi7** [comment]
Usaremos **MySQL** v.8

Para crear la base de datos, desde consola invocaremos a mysql con:

> mysql -u root -p

A continuación crearemos la base de datos con:

> create database oportunistadb character set utf8mb4;

Luego crearemos el usuario que gestionara la base de datos, para que todos tengamos usuario comun y le asignaremos privilegios para que pueda gestionar la base de datos:

> create user 'oportunista'@'localhost' identified by '0p0rtunistA';
> grant all privileges on oportunistadb.* to 'oportunista'@'localhost';
> flush privileges;

**Comment by aadevafi7** [comment]
Para hacer correr MySQL version 8 con pipenv, se ha tenido que hacer modificaciones /home/username/.local/share/virtualenvs/project-env/lib/python3.7/site-packages/django/db/backends/mysql en los ficheros base.py y operations.py

Pasos aqui:
https://stackoverflow.com/questions/55657752/django-installing-mysqlclient-error-mysqlclient-1-3-13-or-newer-is-required

**Comment by kanales** [comment]
Implementado en la rama docker, ver #62 para el pull request. Desafortunadamente no pude aprovechar lo que habia hecho ya en la rama del issue.

**Comment by aadevafi7** [comment]
Finalmente migrada a PostgreeSQL.
