### ISSUE TITLE
Redirección cuando intento de acceso anonimo (backend)

### ISSUE THREAD

**Issue by aadevafi7** [UB-ES-19/F1-Oportunista#84]
Cuando un usuario que no está loggeado intenta acceder alguna sección donde se requiere que este loggeado que se redirija a la página de loggin.

**Comment by kanales** [comment]
https://docs.djangoproject.com/en/1.11/topics/auth/default/#the-login-required-decorator

**Comment by aadevafi7** [comment]
Implementado correspondiente código en settings.py
