### ISSUE TITLE
 Error (no such column: idealista_app_property.op_type) in dev

### ISSUE THREAD

**Issue by SergioUB** [UB-ES-19/F1-Oportunista#88]
Error a la hora de ver tus posts y buscar posts.

The above exception (no such column: idealista_app_property.op_type) was the direct cause of the following exception:
/home/sergio/.local/lib/python3.7/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/contrib/auth/decorators.py in _wrapped_view
                return view_func(request, *args, **kwargs) …
▶ Local vars
/home/sergio/Escritorio/RepoOficialIngSoft/repoSprint3/dev/F1-Oportunista/idealista/idealista_app/views.py in myposts
        return render(request, 'idealista_app/profile/tus-anuncios.html', context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/shortcuts.py in render
    content = loader.render_to_string(template_name, context, request, using=using) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/loader.py in render_to_string
    return template.render(context, request) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/backends/django.py in render
            return self.template.render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in render
                    return self._render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in _render
        return self.nodelist.render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in render_annotated
            return self.render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/loader_tags.py in render
            return compiled_parent._render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in _render
        return self.nodelist.render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in render_annotated
            return self.render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/loader_tags.py in render
                result = block.nodelist.render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/base.py in render_annotated
            return self.render(context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/template/defaulttags.py in render
            len_values = len(values) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/models/query.py in __len__
        self._fetch_all() …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/models/query.py in _fetch_all
            self._result_cache = list(self._iterable_class(self)) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/models/query.py in __iter__
        results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py in execute_sql
            cursor.execute(sql, params) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/backends/utils.py in execute
            return super().execute(sql, params) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/backends/utils.py in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/backends/utils.py in _execute_with_wrappers
        return executor(sql, params, many, context) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/backends/utils.py in _execute
                return self.cursor.execute(sql, params) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/utils.py in __exit__
                raise dj_exc_value.with_traceback(traceback) from exc_value …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/backends/utils.py in _execute
                return self.cursor.execute(sql, params) …
▶ Local vars
/home/sergio/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute
        return Database.Cursor.execute(self, query, params

**Comment by aadevafi7** [comment]
Se estaba ejecutando en dev una base de datos que correspondia a las modificaciones aplicadas a una branch en desarrollo. Se ejecuta la base de datos correspondiente y no da error.
