### ISSUE TITLE
Aplicar items seleccionados en listas para busqueda (frontend)

### ISSUE THREAD

**Issue by aadevafi7** [UB-ES-19/F1-Oportunista#90]
En la home, los items seleccionados en las listas de busqueda que se pasen al clicar en boton Buscar.

**Comment by SergioUB** [comment]
Done.

**Comment by aadevafi7** [comment]
Se ha de mirar que a la hora de pasar los parametros al buscar, en vez de hacer un lowCase del nombre que pille el campo 'acr'.
Por otro lado, se ha de mirar la plantilla "buscar-publicaciones" que era de la rama 81 y salia todo pegado. En esta rama sale mejor, pero se ha de mirar la estructura.

**Comment by aadevafi7** [comment]
Hecho y mergeado
